#!/usr/bin/env bash
#
#    Copyright (c) 2021 quarkyalice (quarkyalice@disroot.org)
#    
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

# === Variables ===
PROGNAME="$(basename "${0}")"
PACMAN_LOG="/var/log/pacman.log"
PORTAGE_LOG="/var/log/emerge.log"

# Getting the install date
if [[ -f /usr/bin/pacman ]]; then
    INSTALL_DATE="$(head -n 1 /var/log/pacman.log | cut -b 2-11)"
elif [[ -f /usr/bin/emerge ]]; then
    INSTALL_DATE="$(head -n 1 /var/log/emerge.log | cut -b 31-43)"
else
    INSTALL_DATE="unknown"
fi

if [[ $INSTALL_DATE == "unknown" ]]; then
    echo "Unknown install date, distro probably unsupported!"
else
    echo $INSTALL_DATE
fi
